### PR TITLE
NameId#SPNameQualifier and AttributeValue#NameId for Shibboleth support

### PR DESCRIPTION
**Pull request by nov**
NameId#SPNameQualifier and AttributeValue#NameId is needed for Shibboleth's "eduPersonTargetedID" attribute.

ref.) https://www.switch.ch/aai/support/documents/attributes/edupersontargetedid/

### CODE REVIEW

**Comment by benoist** [comment]
Is there more coming? :)

**Comment by nov** [comment]
“isMemberOf” attribute support might come later, but I’m still not sure we need to handle it in our IdP..

**Comment by benoist** [comment]
let me know when you want to me create a new version

**Comment by nov** [comment]
I see, thanks!

**Comment by nov** [comment]
Hi, I've added "isMemberOf" attribute support.
I hope it's all I need to support Shibboleth.

Please merge them if you are OK.
Thanks

**Comment by benoist** [comment]
3.1.2 has been pushed

**Comment by nov** [comment]
thanks!

**Pull request merged**
