### PR TITLE
Allow the use of a separate private key to sign messages

### PR DESCRIPTION
**Pull request by lawliet89**
Our IdP requires that we use a separate key to sign our messages. 

Please let me know if I've missed anything (like tests).

### CODE REVIEW

**Comment by benoist** [comment]
Tnx! Perhaps we need to split it up in signing_key and encryption_key, right now it's unclear what the function of the private_key is.

**Comment by lawliet89** [comment]
I've renamed `private_key` to `encryption_key` where appropriate.

**Comment by benoist** [comment]
Looks good to me, I have to find some time to review the breaking changes before I can create a new gem version.

Thank you very much!

**Comment by benoist** [comment]
New version has been pushed

**Pull request merged**
