### PR TITLE
allow iterating multiple certificates on signature verification

### LINKED ISSUE #187: Signature verification with multiple certificates when validating SAML responses
I'm having a problem implementing SP with libsaml.

In libsaml, if the metadata contains multiple certificates and no KeyName is specified in the SAML response, `Saml::Util.verify_xml` will always verify the signature with the first certificate.
https://github.com/digidentity/libsaml/blob/8256fc64900c0ef73deff4ed9938d050e5aec5f4/lib/saml/complex_types/role_descriptor_type.rb#L30

This means that the signature verification will always fail if the second certificate is actually used.
In fact, even IdPs like Google and Azure AD do not specify the KeyName in the SAML response when there are multiple certificates. (KeyName does not even exist in metadata)
This causes the problem that there are times when the user cannot log in during certificate rotation.

How about changing the implementation (or providing it as an option) to try to verify signatures using all certificates included in the metadata?
This idea has been implemented in OSS such as ruby-saml and Keycloak.
https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/response.rb#L884-L898
https://github.com/keycloak/keycloak/blob/8e6489459dac322bbc61b6a63b7cb2d5aa9870af/saml-core/src/main/java/org/keycloak/saml/processing/core/util/XMLSignatureUtil.java#L498-L513

---

I'd like to contribute with a PullRequest, but I'm not familiar with libsam's implementation so it's going to take some time.  I hope someone can help me.

~https://github.com/nhosoya/libsaml/commit/e3be603772419a873602578f6e325703551dafa9~ https://github.com/nhosoya/libsaml/commit/e4ac421100d4fe8c7c38b61cceb9d1712884a8ac
This change is sufficient to solve the problem I'm concerned about, but I still don't fully understand how this change will affect other features of libsaml.

### PR DESCRIPTION
**Pull request by nov**
it is optional & per-provider configurable behaviour

close #187

### CODE REVIEW

**Comment by nov** [comment]
can someone review this pull request?

**Comment by jdongelmans** [comment]
Sorry @nov, I saw the notification earlier this week but completely forgot about it. Thanks for your efforts again :)

**Comment by jdongelmans** [comment]
`Successfully registered gem: libsaml (3.13.0)`

**Comment by nov** [comment]
thanks a lot!

**Pull request merged**
