### PR TITLE
raise Saml::Errors::SignatureMissing when Response element is not signed

### PR DESCRIPTION
**Pull request by nov**
Util#verify_xml should raise Saml::Errors::SignatureMissing when signed node is missing

Originally, "NoMethodError: undefined method `canonicalize' for nil:NilClass" had been raised.
It could reproduced when you've setup Google Workspace without "signed response" mode off.

### CODE REVIEW

**Comment by nov** [comment]
hum, all builds seems failing in ruby 2.7+

**Comment by nov** [comment]
Hi, for some reason, this gem seems broken in ruby 2.7+.

**Comment by jdongelmans** [comment]
Thanks @nov, I will have a look later today!

**Comment by nhosoya** [comment]
> this gem seems broken in ruby 2.7+.

I reproduced the same problem in my local environment.
The problem seems to occur with ActiveSupport 7+.
Explicitly requiring `active_support/xml_mini` in saml.rb solves the problem.

```diff
--- a/lib/saml.rb
+++ b/lib/saml.rb
@@ -1,4 +1,5 @@
 require 'active_support/all'
+require 'active_support/xml_mini'
 require 'active_model'
 require 'saml/base'
 require 'saml/xml_helpers'
```

I haven't looked into what changes in ActiveSupport caused this.

I hope this helps.

**Comment by jdongelmans** [comment]
I have merged this and used the fix by @nhosoya for now. It still works with ActiveSupport versions older than 7.0.0 anyway so fine for now.

I have [released](https://rubygems.org/gems/libsaml/versions/3.12.0) version `3.12.0` to rubygems 🎉

**Pull request merged**
