### PR TITLE
make authn_instant configurable

### PR DESCRIPTION
**Pull request by nov**
ref.) https://communities.ca.com/thread/241759908

### CODE REVIEW

**Comment by benoist** [comment]
Hi Nov,

I don't really mind this feature, however I don't think it's the right solution for the problem described in the ref. 
Basically you should use the Conditions element for setting session periods it contains NotBefore and NotOnOrAfter time stamps.

In the mean time I will merge it.

**Comment by benoist** [comment]
3.0.2 is pushed to rubygems

**Comment by nov** [comment]
Hi,

I'm not a SAML expert, but OpenID Connect expert.
In my understanding, SAML's "AuthnInstant" is what called "auth_time" in OpenID Connect, which SP/RP should check when they requested "ForceAnthN=true" ("max_age=0" in OpenID Connect)

But I'm not surprized if I'm wrong.

I'll investigate Conditions element later.

thanks!

**Comment by nov** [comment]
According to the SAML spec, `Conditions#NotBefore` and `Conditions#NotOnOrAfter` are talking about the time-range during which the assertion is valid, so it's a kind of session period "on IdP-side".

However, if SP is requesting `ForceAnthN=true`, SP want to ensure the `ForceAuthN` is properly executed on IdP-side by verifying `AuthnInstant`.
In that case, even the assertion is valid on IdP-side, the authentication result isn't acceptable by SP.
(ex. if End-User removed `ForceAnthN=true` attribute from the SAML AuthN request, such assertion can be easily generated, because SAML request is often not-signed)

http://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf

So `Conditions` response element isn't what for `ForceAnthN=true` request.

**Comment by benoist** [comment]
The conditions are indeed for the session period set by the IdP, but I don't really understand why you would want to set a custom time for the AuthnInstant.
With ForceAuthN we normally terminate the session and issue a new Assertion with a new AuthnStatement so it would get a new time as well. This would allow the SP to verify the authentication was renewed.

As a side note, we always require AuthnRequests to be signed as this eliminates a lot of risk with altering the AuthnRequest, but I'm really curious to read about the issue you have run in to with allowing unsigned AuthnRequests.

**Pull request merged**
